# Generated by Django 4.2.11 on 2024-04-29 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
                ('img', models.ImageField(upload_to='blogs-category')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField()),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Mobile_Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=220)),
                ('mobile_service_heading', models.CharField(max_length=50)),
                ('description1', models.TextField()),
                ('description2', models.TextField()),
                ('description3', models.TextField()),
                ('description4', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('img', models.ImageField(upload_to='pics')),
                ('support_img_1', models.ImageField(upload_to='pics/support-1')),
                ('support_img_2', models.ImageField(upload_to='pics/support-2')),
                ('category', models.CharField(choices=[('Web design', 'Web design'), ('Other', 'Other')], default='Web design', max_length=50)),
                ('client', models.CharField(default='After Nepal', max_length=100)),
                ('project_date', models.DateField()),
                ('project_url', models.URLField(default='')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Web_Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=220)),
                ('web_service_heading', models.CharField(max_length=50)),
                ('description1', models.TextField()),
                ('description2', models.TextField()),
                ('description3', models.TextField()),
                ('description4', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('description', models.TextField()),
                ('imp_description', models.TextField()),
                ('img', models.ImageField(upload_to='my-blog')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.blog_category')),
            ],
        ),
    ]
